/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import kasir.Pembayaran;
import kasir.Kebab;

/**
 *
 * @author rizky
 */
public class Main extends javax.swing.JFrame {
    
    Kebab kebab = new Kebab();
    Pembayaran bayar = new Pembayaran();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        cmbMenu.addItem("PILIH");
        cmbMenu.addItem("Kebab Daging Sapi");
        cmbMenu.addItem("Kebab Daging Ayam");
        
        cmbMetode.addItem("PILIH");
        cmbMetode.addItem("Cash");
        cmbMetode.addItem("GoPay");
        
        nonAktifPesanan();
        nonAktifPembayaran();

    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(95,102,113));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(34,40,49));
    }
    
    private void nonAktifPesanan(){
        rbS.setEnabled(false);
        rbM.setEnabled(false);
        rbL.setEnabled(false);
        tHarga.setEnabled(false);
        spJumlahBeli.setEnabled(false);
        tTotal.setEnabled(false);
        btnAdd.setEnabled(false);
    }
    
    private void aktifUkuran(){
        rbS.setEnabled(true);
        rbM.setEnabled(true);
        rbL.setEnabled(true);
 
    }
    
    private void bersih(){
        nonAktifPesanan();
        bgUkuran.clearSelection();
        tHarga.setText("");
        spJumlahBeli.setValue(0);
        tTotal.setText("");
    }
    
    private void nonAktifPembayaran(){
        tSubtotal.setEnabled(false);
        tDiskon.setEnabled(false);
        tPajak.setEnabled(false);
        tTotalBayar.setEnabled(false);
        tNamaPembeli.setEnabled(false);
        cmbMetode.setEnabled(false);
        tUangBayar.setEnabled(false);
        tUangKembali.setEnabled(false);
    }
    
    private void aktifPembayaran(){
        tSubtotal.setEnabled(true);
        tDiskon.setEnabled(true);
        tPajak.setEnabled(true);
        tTotalBayar.setEnabled(true);
        tNamaPembeli.setEnabled(true);
    }
    
    private void bersihPembayaran(){
        tSubtotal.setText("");
        tDiskon.setText("");
        tPajak.setText("");
        tTotalBayar.setText("");
        tNamaPembeli.setText("");
        cmbMetode.setSelectedItem("PILIH");
        tUangBayar.setText("");
        tUangKembali.setText("");
    }
    
    private void bersihCetak(){
        bersih();
        nonAktifPesanan();
        bersihPembayaran();
        nonAktifPembayaran();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgUkuran = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnKasir = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbMenu = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        rbS = new javax.swing.JRadioButton();
        rbM = new javax.swing.JRadioButton();
        rbL = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        tHarga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        spJumlahBeli = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        tTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tDiskon = new javax.swing.JTextField();
        tPajak = new javax.swing.JTextField();
        tTotalBayar = new javax.swing.JTextField();
        cmbMetode = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tNamaPembeli = new javax.swing.JTextField();
        tUangBayar = new javax.swing.JTextField();
        tUangKembali = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        bCetak = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        tSubtotal = new javax.swing.JTextField();
        bHitung = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKeranjang = new javax.swing.JTable();
        BHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(34, 40, 49));

        btnDashboard.setBackground(new java.awt.Color(95, 102, 113));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDashboardMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home_4.png"))); // NOI18N

        javax.swing.GroupLayout btnDashboardLayout = new javax.swing.GroupLayout(btnDashboard);
        btnDashboard.setLayout(btnDashboardLayout);
        btnDashboardLayout.setHorizontalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDashboardLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        btnDashboardLayout.setVerticalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnDashboardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnMenu.setBackground(new java.awt.Color(34, 40, 49));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Restaurant_1.png"))); // NOI18N

        javax.swing.GroupLayout btnMenuLayout = new javax.swing.GroupLayout(btnMenu);
        btnMenu.setLayout(btnMenuLayout);
        btnMenuLayout.setHorizontalGroup(
            btnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMenuLayout.setVerticalGroup(
            btnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnKasir.setBackground(new java.awt.Color(34, 40, 49));
        btnKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKasirMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kasir");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Checkout_4.png"))); // NOI18N

        javax.swing.GroupLayout btnKasirLayout = new javax.swing.GroupLayout(btnKasir);
        btnKasir.setLayout(btnKasirLayout);
        btnKasirLayout.setHorizontalGroup(
            btnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKasirLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnKasirLayout.setVerticalGroup(
            btnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnKasirLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Swivel_2.png"))); // NOI18N

        btnKeluar.setBackground(new java.awt.Color(255, 0, 0));
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKeluarMousePressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Keluar");

        javax.swing.GroupLayout btnKeluarLayout = new javax.swing.GroupLayout(btnKeluar);
        btnKeluar.setLayout(btnKeluarLayout);
        btnKeluarLayout.setHorizontalGroup(
            btnKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKeluarLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel24)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        btnKeluarLayout.setVerticalGroup(
            btnKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKeluarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel24)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Swivel_4.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Kasir Penjualan Kebab");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel9)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Kebab Daging Sapi", "S", "Rp. 10.000"},
                {null, "M", "Rp. 15.000"},
                {null, "L", "Rp. 21.000"},
                {null, null, null},
                {"Kebab Daging Ayam", "S", "Rp. 8.000"},
                {null, "M", "Rp. 12.000"},
                {null, "L", "Rp. 18.000"},
                {null, null, null}
            },
            new String [] {
                "Nama", "Ukuran", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1)
                .addGap(60, 60, 60))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "PESANAN"));

        jLabel10.setText("Menu:");

        cmbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMenuActionPerformed(evt);
            }
        });

        jLabel11.setText("Ukuran:");

        bgUkuran.add(rbS);
        rbS.setText("S");
        rbS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSActionPerformed(evt);
            }
        });

        bgUkuran.add(rbM);
        rbM.setText("M");
        rbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMActionPerformed(evt);
            }
        });

        bgUkuran.add(rbL);
        rbL.setText("L");
        rbL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLActionPerformed(evt);
            }
        });

        jLabel12.setText("Jumlah Beli:");

        tHarga.setEditable(false);

        jLabel13.setText("Harga:");

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        spJumlahBeli.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spJumlahBeli.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spJumlahBeliStateChanged(evt);
            }
        });

        jLabel14.setText("Total");

        tTotal.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(rbS)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbM)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbL))
                                .addComponent(tHarga))
                            .addComponent(spJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rbS)
                    .addComponent(rbM)
                    .addComponent(rbL))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnAdd)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "PEMBAYARAN"));

        jLabel15.setText("Diskon 10%:");

        jLabel16.setText("Metode: ");

        jLabel17.setText("PPN 12%:");

        jLabel18.setText("Total Bayar:");

        tDiskon.setEditable(false);

        tPajak.setEditable(false);

        tTotalBayar.setEditable(false);

        cmbMetode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodeActionPerformed(evt);
            }
        });

        jLabel19.setText("Nama Pembeli: ");

        jLabel20.setText("Uang Bayar:");

        jLabel21.setText("Uang Kembali:");

        tNamaPembeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNamaPembeliKeyPressed(evt);
            }
        });

        tUangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tUangBayarKeyPressed(evt);
            }
        });

        tUangKembali.setEditable(false);

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("*min. 5 pembelian");

        bCetak.setText("Cetak");
        bCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakActionPerformed(evt);
            }
        });

        jLabel23.setText("SubTotal:");

        tSubtotal.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tSubtotal)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tPajak)
                            .addComponent(tDiskon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(73, 73, 73))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(tNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tUangKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(tUangBayar)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbMetode, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(bCetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(tNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel16)
                    .addComponent(cmbMetode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel17)
                    .addComponent(tPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tUangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(tTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bCetak)
                .addGap(17, 17, 17))
        );

        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        tableKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deskripsi", "Ukuran", "Harga", "Jumlah", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableKeranjang.getTableHeader().setReorderingAllowed(false);
        tableKeranjang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tableKeranjangPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tableKeranjang);
        if (tableKeranjang.getColumnModel().getColumnCount() > 0) {
            tableKeranjang.getColumnModel().getColumn(0).setMinWidth(150);
            tableKeranjang.getColumnModel().getColumn(0).setPreferredWidth(150);
            tableKeranjang.getColumnModel().getColumn(0).setMaxWidth(150);
            tableKeranjang.getColumnModel().getColumn(1).setMinWidth(50);
            tableKeranjang.getColumnModel().getColumn(1).setPreferredWidth(50);
            tableKeranjang.getColumnModel().getColumn(1).setMaxWidth(50);
            tableKeranjang.getColumnModel().getColumn(3).setMinWidth(50);
            tableKeranjang.getColumnModel().getColumn(3).setPreferredWidth(50);
            tableKeranjang.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(bHitung)
                                .addGap(106, 106, 106)
                                .addComponent(BHapus)
                                .addGap(12, 12, 12)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bHitung)
                            .addComponent(BHapus)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("tab4", jPanel3);

        bg.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, -40, 760, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        setColor(btnDashboard);
        resetColor(btnMenu);
        resetColor(btnKasir);
        btnKeluar.setBackground(new Color(255,0,0));

    }//GEN-LAST:event_btnDashboardMousePressed

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        setColor(btnMenu);
        resetColor(btnDashboard);
        resetColor(btnKasir);
        btnKeluar.setBackground(new Color(255,0,0));

    }//GEN-LAST:event_btnMenuMousePressed

    private void btnKasirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        setColor(btnKasir);
        resetColor(btnDashboard);
        resetColor(btnMenu);
        btnKeluar.setBackground(new Color(255,0,0));

    }//GEN-LAST:event_btnKasirMousePressed

    private void cmbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMenuActionPerformed
        // TODO add your handling code here:
        bersih();
        kebab.setNama(cmbMenu.getSelectedItem().toString());
        if (kebab.getNama().equalsIgnoreCase("PILIH")) {
            nonAktifPesanan();
        }else{
            aktifUkuran();
        }
    }//GEN-LAST:event_cmbMenuActionPerformed

    private void rbSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSActionPerformed
        // TODO add your handling code here:
        kebab.setUkuran(rbS.getText());
        tHarga.setEnabled(true);
        tHarga.setText(Double.toString(kebab.getHarga()));
        spJumlahBeli.setEnabled(true);
        spJumlahBeli.setValue(0);
    }//GEN-LAST:event_rbSActionPerformed

    private void rbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMActionPerformed
        // TODO add your handling code here:
        kebab.setUkuran(rbM.getText());
        tHarga.setEnabled(true);
        tHarga.setText(Double.toString(kebab.getHarga()));
        spJumlahBeli.setEnabled(true);
        spJumlahBeli.setValue(0);
    }//GEN-LAST:event_rbMActionPerformed

    private void rbLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLActionPerformed
        // TODO add your handling code here:
        kebab.setUkuran(rbL.getText());
        tHarga.setEnabled(true);
        tHarga.setText(Double.toString(kebab.getHarga()));
        spJumlahBeli.setEnabled(true);
        spJumlahBeli.setValue(0);
    }//GEN-LAST:event_rbLActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (cmbMenu.getSelectedItem().equals("PILIH") ||
            bgUkuran.getSelection() == null ||
            tHarga.getText().isEmpty() ||
            ((int) spJumlahBeli.getValue() <= 0 ||
                tTotal.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Semua kolom pesanan harus diisi", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;

        }else{
            DefaultTableModel model = (DefaultTableModel) tableKeranjang.getModel();
            
            String menu = kebab.getNama();
            String ukuran = kebab.getUkuran();
            
            boolean isSame = false;
            for (int i = 0; i < model.getRowCount(); i++){
                String menuTabel = model.getValueAt(i, 0).toString();
                String ukuranTabel = model.getValueAt(i, 1).toString();
                
                if (menu.equalsIgnoreCase(menuTabel) && ukuran.equalsIgnoreCase(ukuranTabel)) {
                    int jumlahLama = Integer.parseInt(model.getValueAt(i, 3).toString());
                    int jumlahGabung = jumlahLama + kebab.getJumlahBeli();
                    double totalGabung = jumlahGabung * kebab.getHarga();
                    
                    model.setValueAt(jumlahGabung, i, 3);
                    model.setValueAt(totalGabung, i, 4);
                    isSame = true;
                    break;
                }
            }
            
            if (!isSame) {
                model.addRow(new Object[]{
                    kebab.getNama(),
                    kebab.getUkuran(),
                    kebab.getHarga(),
                    kebab.getJumlahBeli(),
                    kebab.getTotal(),    
                });
            }

            bersih();
            cmbMenu.setSelectedItem("PILIH");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void spJumlahBeliStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spJumlahBeliStateChanged
        // TODO add your handling code here:
        kebab.setJumlahBeli((Integer) spJumlahBeli.getValue());;
        tTotal.setEnabled(true);

        if (kebab.getJumlahBeli() == 0) {
            tTotal.setText("");
        }else{
            tTotal.setText(Double.toString(kebab.getTotal()));
            btnAdd.setEnabled(true); 
        }

    }//GEN-LAST:event_spJumlahBeliStateChanged

    private void cmbMetodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodeActionPerformed
        // TODO add your handling code here:
        bayar.setMetode(cmbMetode.getSelectedItem().toString());
        tUangBayar.setText("");
        tUangKembali.setText("");
        if (bayar.getMetode().equalsIgnoreCase("PILIH")) {
            tUangBayar.setEnabled(false);
            tUangKembali.setEnabled(false);
        }else if (bayar.getMetode().equalsIgnoreCase("Cash")) {
            tUangBayar.setEnabled(true);
            tUangBayar.requestFocus();
        }else{
            tUangBayar.setEnabled(true);
            bayar.setUangBayar(bayar.getTotalBayar());
            tUangBayar.setText(Double.toString(bayar.getUangBayar()));
            tUangKembali.setText(Double.toString(bayar.getUangKembali()));
        }
    }//GEN-LAST:event_cmbMetodeActionPerformed

    private void tNamaPembeliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNamaPembeliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bayar.setNamaPembeli(tNamaPembeli.getText());
            cmbMetode.setEnabled(true);
            cmbMetode.requestFocus();
        }else{
            return;
        }
    }//GEN-LAST:event_tNamaPembeliKeyPressed

    private void tUangBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tUangBayarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                bayar.setUangBayar(Double.parseDouble(tUangBayar.getText()));
                tUangKembali.setText(Double.toString(bayar.getUangKembali()));
                if (bayar.getUangBayar() < bayar.getTotalBayar()) {
                    JOptionPane.showMessageDialog(null, "Pembayaran Kurang!",
                        "Warning", JOptionPane.OK_OPTION);
                    tUangBayar.setText("");
                    tUangKembali.setText("");
                    tUangKembali.setEnabled(false);
                }else{
                    tUangKembali.setEnabled(true);
                    bCetak.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Input tidak valid!");
                return;
            }
        }else{
            return;
        }
    }//GEN-LAST:event_tUangBayarKeyPressed

    private void bCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableKeranjang.getModel();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Keranjang masih kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }else if (tNamaPembeli.getText().isEmpty() ||
            cmbMetode.getSelectedItem().equals("PILIH") ||
            tUangBayar.getText().isEmpty() ||
            tUangKembali.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua kolom pembayaran harus diisi", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;

        }else{
            System.out.println("\n========================== STRUK PEMBELIAN ==========================");
            System.out.println("Tanggal/Waktu       : " +
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")));

            System.out.printf("%-20s %-10s %-9s %-10s %-10s\n",
                "Deskripsi", "Ukuran", "Harga", "Jumlah", "Total");
            System.out.println("=====================================================================");
            for (int i = 0; i < model.getRowCount() ; i++) {
                String deskripsi = model.getValueAt(i, 0).toString();
                String ukuran = model.getValueAt(i, 1).toString();
                String harga = model.getValueAt(i, 2).toString();
                String jumlah = model.getValueAt(i, 3).toString();
                String total = model.getValueAt(i, 4).toString();

                System.out.printf("%-20s %-10s %-9s %-10s %-10s\n",
                    deskripsi, ukuran, harga, jumlah, total);
            }
            System.out.println("=====================================================================");

            System.out.println("Subtotal            : " + bayar.getSubTotal());
            if (bayar.getDiskon() > 0) {
                System.out.println("Diskon 10%          : " + bayar.getDiskon());
            }
            System.out.println("PPN 12%             : " + bayar.getPajak());
            System.out.println("Total Bayar         : " + bayar.getTotalBayar());
            System.out.println("Nama Pembeli        : " + bayar.getNamaPembeli());
            System.out.println("Metode              : " + bayar.getMetode());
            System.out.println("Uang Bayar          : " + bayar.getUangBayar());
            if (bayar.getUangKembali() > 0) {
                System.out.println("Uang Kembali        : " + bayar.getUangKembali());
            }

            System.out.println("=========================== TERIMA KASIH ============================\n");

            bersihCetak();
            model.setRowCount(0);
        }
    }//GEN-LAST:event_bCetakActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableKeranjang.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Keranjang Kosong!");
            nonAktifPembayaran();
            bersihPembayaran();
            return;
        }else{
            aktifPembayaran();
            double totalHarga = 0;
            int totalItem = 0;

            for (int i = 0; i < model.getRowCount(); i++) {
                int jumlah = Integer.parseInt(model.getValueAt(i, 3).toString()); 
                double subtotal = Double.parseDouble(model.getValueAt(i, 4).toString()); 
                totalItem += jumlah;
                totalHarga += subtotal;
            }

            bayar.setSubTotal(totalHarga);
            bayar.hitungDiskon(totalItem);
            bayar.hitungPajak();
            bayar.hitungTotalBayar();

            // tampil di field
            tSubtotal.setText(Double.toString(bayar.getSubTotal()));
            tDiskon.setText(Double.toString(bayar.getDiskon()));
            tPajak.setText(Double.toString(bayar.getPajak()));
            tTotalBayar.setText(Double.toString(bayar.getTotalBayar()));
            tNamaPembeli.requestFocus();
        }
    }//GEN-LAST:event_bHitungActionPerformed

    private void tableKeranjangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tableKeranjangPropertyChange
        // TODO add your handling code here:
        int row = tableKeranjang.getSelectedRow();

        if (row != -1) {
            try {
                double harga = Double.parseDouble(tableKeranjang.getValueAt(row, 2).toString());
                int jumlah = Integer.parseInt(tableKeranjang.getValueAt(row, 3).toString());
                if (jumlah > 0) {
                    double total = jumlah * harga;

                    tableKeranjang.setValueAt(total, row, 4);
                }else{
                    JOptionPane.showMessageDialog(this, "Input tidak valid!");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Input tidak valid!");
            }

        }
    }//GEN-LAST:event_tableKeranjangPropertyChange

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        int row = tableKeranjang.getSelectedRow();

        if (row != -1) {
            DefaultTableModel model = (DefaultTableModel) tableKeranjang.getModel();
            model.removeRow(row);
            if (tableKeranjang.getRowCount() == 0) {
                nonAktifPembayaran();
                bersihPembayaran();
                return;
            }else{
                aktifPembayaran();
            }

        }else{
            JOptionPane.showMessageDialog(this, "Pilih item yang ingin dihapus!");
        }
    }//GEN-LAST:event_BHapusActionPerformed

    private void btnKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMousePressed
        // TODO add your handling code here:
        btnKeluar.setBackground(new Color(150,0,0));
        int x;
        x = JOptionPane.showConfirmDialog(null, "Keluar?", "Konfirm", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            dispose();
        }else{
            btnKeluar.setBackground(new Color(255,0,0));
            return;

        }
    }//GEN-LAST:event_btnKeluarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHapus;
    private javax.swing.JButton bCetak;
    private javax.swing.JButton bHitung;
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup bgUkuran;
    private javax.swing.JButton btnAdd;
    private javax.swing.JPanel btnDashboard;
    private javax.swing.JPanel btnKasir;
    private javax.swing.JPanel btnKeluar;
    private javax.swing.JPanel btnMenu;
    private javax.swing.JComboBox<String> cmbMenu;
    private javax.swing.JComboBox<String> cmbMetode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbL;
    private javax.swing.JRadioButton rbM;
    private javax.swing.JRadioButton rbS;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JSpinner spJumlahBeli;
    private javax.swing.JTextField tDiskon;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tNamaPembeli;
    private javax.swing.JTextField tPajak;
    private javax.swing.JTextField tSubtotal;
    private javax.swing.JTextField tTotal;
    private javax.swing.JTextField tTotalBayar;
    private javax.swing.JTextField tUangBayar;
    private javax.swing.JTextField tUangKembali;
    private javax.swing.JTable tableKeranjang;
    // End of variables declaration//GEN-END:variables
}
